version: 2
jobs:
   j8_current:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test current version
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: convergence

   j8_spring_next:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test Spring.NEXT
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: spring5-next,convergence

   j8_spring51_next:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test Spring.NEXT 5.1
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: spring51-next,convergence

   j10_current:
     docker:
       - image: circleci/openjdk:10.0.1-jdk-node-browsers
     steps:
        - checkout
        - run:
            name: Java 10 - Test current version
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: java10,convergence

   j10_spring_next:
     docker:
       - image: circleci/openjdk:10.0.1-jdk-node-browsers
     steps:
        - checkout
        - run:
            name: Java 10 - Test Spring.NEXT
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: spring5-next,java10,convergence

   j10_spring51_next:
     docker:
       - image: circleci/openjdk:10.0.1-jdk-node-browsers
     steps:
        - checkout
        - run:
            name: Java 10 - Test Spring.NEXT 5.1
            command: mvn clean dependency:list test -P${PROFILE} -Dsort
            environment:
              PROFILE: spring51-next,java10,convergence

   deploy:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Deploy to Artifactory
            command: ./deploy.bash

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - j8_current
      - j8_spring_next
      - j8_spring51_next
      - j10_current
      - j10_spring_next
      - j10_spring51_next
      - deploy:
          requires:
            - j8_current
            - j8_spring_next
            - j8_spring51_next
            - j10_current
            - j10_spring_next
            - j10_spring51_next

general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

dependencies:
  cache_directories:
    - "~/.m2"
